### ISSUE TITLE
Sample request - dynamic editing

### ISSUE THREAD

**Issue by Alicia-Hong** [GDEED/RV_Root#20]
Pain point: we need to communicate workshop information to the participants (https://pastevents.realityvirtuallyhack.com/workshops/). What we experienced in the past is that many of the workshop leads send us their information at last minute, which result in delay in updating the whole section of the website. It is also a redundant manual effort to move their text from the email to the website. Coordination of time and adding missing info is also a pain. (e.g. a 3D software workshop requested attendees to bring mouse and pre-install their software) 

Proposed solution: When we invite a person to do workshop, we want to be able to send them a google spreadsheet to request information immediately. Once they fill it out the information will show up in the respective section of the website real-time (in case they send last minute info to us 3 hours before the workshop day, which has happened in the past). Another preferred feature (not-a-must) is having an scheduling algorithm to automatically arrange workshop leads preferred time slots into the day. 

Things can be on the google sheet:
1) Your name
2) Your orgnization
3) Title of your workshop
4) Description of your workshop
5) Your preferred time slot
6) Optional - extra notes

**Comment by mcclaskiem** [comment]
Given how Zeppelin is configured, building a real-time solution for managing content on the site is going to require a lot of custom dev work. With that said, given people's availability and knowing the other features we definitely need to build I dont know how much we can prioritize this. 

Right now content is managed using YML files which can be edited by anyone without any coding knowledge. We could very easily add "non-developers" to the Github repo and they will be able to edit the content right on the Github website and then publish it immediately to the live website. This seems like a good fallback since we could dedicate one person to manage the content and be on call to make updates in "real-time".

With regards to the second preferred feature. Is the ask to simple re-arrange the page based on the time of day for the users viewing it or is this to allow workshop leads to change around what time they want to present in real-time?

Let me know if you have any questions!


CC: @cwrage77 @Rjected @stevep2007

**Comment by mcclaskiem** [comment]
I know we have discussed a better notification system that is more real-time, potentially via SMS or Email so that would definitely help with notifying participants of updates as things change.

As for updating the website the same issue still applies where we would need to edit via the config files and therefore would require someone to be on call to make updates the day of the event.

**Comment by mcclaskiem** [comment]
Closing this as it was a test issue
