### ISSUE TITLE
Add a sponsor page

### ISSUE THREAD

**Issue by Rjected** [GDEED/RV_Root#22]
Create a page listing sponsors and their respective sponsorship tiers, add sponsors and their respective tiers as they are confirmed.

**Comment by bmodur** [comment]
I have added code(.Html,.yml etc)and would like to open up a pull request for team lead to to review.

**Comment by Rjected** [comment]
@bmodur feel free to open a pull request, make sure to reference this issue if you've solved it (for example the pull request name can be "added sponsor page: fixes #22")

**Comment by bmodur** [comment]
FYI,
It has been a while since i logged in.I have been busy with a few other things.I had given all the source code that i had created for the sponsor page to pablo and had copied Steve mentioning that a few hooks ups were needed and i could not meet the oct 1 dead line. I do see that pablo has completed that and the page gets loaded.Thanks to pablo for those extra things.

**Comment by Rjected** [comment]
Closing since sponsor page is added with PR #57
