### ISSUE TITLE
Mentor page  design

### ISSUE THREAD

**Issue by Seguda** [GDEED/RV_Root#227]
Based on the David's email the relevant information we need to display are below. I added all the relevant information for mentors to mentor.yml but it doesn't show up, only mentor's image, name/surname, bio and linkedin/website info are showing up. 

Your Organization
Your Title
Which of these broad categories do your skills fit in?
What are the tools/languages/platforms that you consider yourself strong or expert in?
Your Bio
Photo
Linkedin
Website
Other link

**Comment by stevep2007** [comment]
The design of the mentor page lists bulleted high-level skills in addition to the biography. Participants can readily identify the mentor that they need to work with.  @Seguda was unable to present the bulleted skills. 

I will ask David to share the data set so that @mcclaskiem  can  debug against the actual data.

**Comment by mcclaskiem** [comment]
@Seguda I just pushed a branch called `feature/mentor-skill-list`. If you look at the commit logs you will see that I changed the skills attribute to be an array. In the `mentor_inner.html` template you will see I added a new loop that traverses the new skills array and echos them out! Let me know if you have any questions!

CC: @stevep2007

**Comment by Seguda** [comment]
Thanks @mcclaskiem I'm updating the rest of list.
