### ISSUE TITLE
Can the length of the About page be increased?

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#46]
@mcclaskiem @Zlerp 

We have a problem with the length of the about page. It prevents styling of the fonts and layout by Zach and Jenna.

The result of making the font smaller to fit everything on the page makes it hard to read. This page is supposed to convince people to sponsor, apply, and mentor.

**Comment by stevep2007** [comment]
@mcclaskiem @Zlerp 

I spoke with Giorgio Natali who built https://github.com/SwiftFest/swiftfest-site/commit/4c095887383bca9e8d39263f715e3755de758344

He has not increased page length but had made similar modifications and believes that it is possible to increase the legnth of the **About** page.

**Comment by mcclaskiem** [comment]
Hey @stevep2007  My recommendation is that we massage the content to be more visual or broken out better on the About page rather than trying to make one big block of text look nice. 

An example would be to bucket the main talking points down to 3-5 core things and use the alternating layout which included images and a short write up. See screenshot below:

![screen shot 2018-10-03 at 10 47 13 am](https://user-images.githubusercontent.com/6970287/46418433-c93a5600-c6f9-11e8-8446-ef6931791912.png)

We could have a block on "Diversity" one on "Teams", etc. Also if there are other content blocks either on the default about page or on other pages of the site we can repurpose them on this page or any page moving forward.

**Comment by stevep2007** [comment]
@mcclaskiem I have no idea about the constraints for rewriting this. 

This is based on the document https://docs.google.com/document/d/1P_WXyFLbJ_YFDbQgwV_82lltd_kJQl9pXRz-eEAbgxY/edit?usp=sharing

Which after many iterations was edited and then agreed and approved by Media Lab comms. It is a clear specification. 

Using dev tools I was able to insert another section and had no problem with the responsive design.

**Comment by mcclaskiem** [comment]
Closing as About Page has been updated with new content.
