### ISSUE TITLE
Application page comments and clarifications

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#75]
Left justify field names

Add the clarification: (City, State/County, Country) to What is your current location with the fields

AR/VR Experience - Other- should be a checkbox and the field should be annotated - if you checked other, please describe your experience,

Affiliation would be more understandable if it were written: Affiliation i.e. university name, employer name, institution name

File upload needs a progress bar or a spinner.

There are fields in the sheet that do not map into the form fields.

**Comment by mcclaskiem** [comment]
@cwrage77 @mayyapillai We can add a class to the body tag while the file is uploading. That class will change the mouse pointer to the progress indicator which will show user something is happening. Code block below:

`.loading {
    cursor: progress;
}`

This class should go with the rest of our global styles and then can be added to any element. The body will be best since that will prevent the user from clicking around while things are uploading.

**Comment by mcclaskiem** [comment]
@stevep2007 I think most of these updates have been made from a UI perspective. Are some fields still not mapping to the form?
